# Generated by Django 5.0 on 2023-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Bank'), (3, 'Mix')], default=1),
        ),
    ]
